// <auto-generated />
using System;
using Boilerplate.Infrastructure.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Boilerplate.Infrastructure.Migrations
{
    [DbContext(typeof(BoilerplateDBContext))]
    [Migration("20240123092212_Initial-Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Boilerplate.Core.Entities.AppSettings.AppSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit")
                        .HasColumnName("is_system");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("key");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Key" }, "key_unique")
                        .IsUnique()
                        .HasFilter("[key] IS NOT NULL");

                    b.ToTable("app_settings");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsSystem = true,
                            Key = "email_configuration",
                            Value = "{\"From\":\"digitalhub_dev@outlook.com\",\"SmtpServer\":\"smtp-mail.outlook.com\",\"Port\":\"587\",\"UserName\":\"digitalhub_dev@outlook.com\",\"Password\":\"DigitalDevTeam@123\"}"
                        },
                        new
                        {
                            Id = 2L,
                            IsSystem = true,
                            Key = "complete_migration_email",
                            Value = " تم رفع الملف ( {0} )بنجاح  "
                        },
                        new
                        {
                            Id = 3L,
                            IsSystem = true,
                            Key = "uncomplete_migration_email",
                            Value = " لم يتم رفع الملف  ( {0} ) لوجود اخطاء بالشيت ({1}) بالصف {2} والعمود {3}؛فلابد من مراجعة النشرة ثم قم بإعادة الرفع مره اخرى "
                        });
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.Auth.Roles.RoleTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("locale");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "Locale")
                        .IsUnique()
                        .HasFilter("[role_id] IS NOT NULL");

                    b.ToTable("role_translations");
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.Auth.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("birth_date");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<int>("Degree")
                        .HasColumnType("int")
                        .HasColumnName("degree");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("first_name");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("gender");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit")
                        .HasColumnName("is_banned");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit")
                        .HasColumnName("is_system");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_verified");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("path");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ResetCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("reset_code");

                    b.Property<DateTime>("ResetTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("reset_time");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_url");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserName", "Email")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL AND [Email] IS NOT NULL");

                    b.ToTable("Users", "security");

                    b.HasData(
                        new
                        {
                            Id = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e3b9c8c2-31c8-4899-99c4-6ebc51e2542b",
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            Degree = 0,
                            Email = "amalassem21@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            Gender = 1,
                            IsBanned = false,
                            IsSystem = false,
                            IsVerified = false,
                            LastName = "Admin",
                            LockoutEnabled = true,
                            NormalizedEmail = "AMALASSEM21@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAECi3lT6l+1HKEawLjldUyT9Azn1jpzQZeMkapDbycmjUT++jy2voAG5zGBg4Spj+iA==",
                            PhoneNumber = "01145907543",
                            PhoneNumberConfirmed = true,
                            ResetTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "SLKWB2MKZHIHR3TK4VHZYLZSAMIKAUCF",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.Departments.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.Departments.DepartmentTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("department_id");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("locale");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId", "Locale")
                        .IsUnique();

                    b.ToTable("department_translations");
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.Departments.DepartmentUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("department_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsManager")
                        .HasColumnType("bit")
                        .HasColumnName("is_manager");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId", "DepartmentId")
                        .IsUnique()
                        .HasFilter("[user_id] IS NOT NULL");

                    b.ToTable("department_users");
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.Elements.Element", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.Property<string>("key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("key");

                    b.HasKey("Id");

                    b.HasIndex("key")
                        .IsUnique();

                    b.ToTable("elements");
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.Elements.ElementTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<long>("ElementId")
                        .HasColumnType("bigint")
                        .HasColumnName("element_id");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("locale");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ElementId", "Locale")
                        .IsUnique();

                    b.ToTable("element_translations");
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.FilesLibrary.FilesLibrary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("file");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("file_name");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("file_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("thumbnail");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.Property<string>("directory")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("directory");

                    b.HasKey("Id");

                    b.ToTable("files_library");
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.Languages.Language", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<string>("Direction")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("direction");

                    b.Property<string>("Flag")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("flag");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit")
                        .HasColumnName("is_system");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("locale");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Locale")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("languages");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            Direction = "rtl",
                            Flag = "eg",
                            IsDefault = true,
                            IsDeleted = false,
                            IsSystem = true,
                            Locale = "ar",
                            Name = "العربية",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            Direction = "ltr",
                            Flag = "us",
                            IsDefault = false,
                            IsDeleted = false,
                            IsSystem = true,
                            Locale = "en",
                            Name = "الإنجليزية",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        });
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.Languages.LanguageTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint")
                        .HasColumnName("language_id");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("locale");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId", "Locale")
                        .IsUnique();

                    b.ToTable("language_translations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            LanguageId = 1L,
                            Locale = "en",
                            Name = "Arabic",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            LanguageId = 2L,
                            Locale = "en",
                            Name = "English",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        });
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.Migrations.Migration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error");

                    b.Property<int>("ErrorColumn")
                        .HasColumnType("int")
                        .HasColumnName("error_column");

                    b.Property<int>("ErrorRow")
                        .HasColumnType("int")
                        .HasColumnName("error_row");

                    b.Property<string>("ErrorSheet")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_sheet");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_name");

                    b.Property<string>("FileUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_url");

                    b.Property<string>("MigrationStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("migration_status");

                    b.Property<int>("NoSheets")
                        .HasColumnType("int")
                        .HasColumnName("no_sheets");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("migrations");
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.PermissionModule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("permission_modules");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Departments",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Users",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Roles",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Permissions",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Settings",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Languages",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2023, 2, 20, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Department Users",
                            UpdatedAt = new DateTime(2023, 2, 20, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2023, 2, 20, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Dashboard",
                            UpdatedAt = new DateTime(2023, 2, 20, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        });
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.RolePermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<long>("ModuleId")
                        .HasColumnType("bigint")
                        .HasColumnName("module_id");

                    b.Property<long>("OperationId")
                        .HasColumnType("bigint")
                        .HasColumnName("operation_id");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("RoleId");

                    b.ToTable("role_permission");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 1L,
                            OperationId = 1L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 1L,
                            OperationId = 2L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 1L,
                            OperationId = 3L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 1L,
                            OperationId = 4L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 1L,
                            OperationId = 5L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 2L,
                            OperationId = 1L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 2L,
                            OperationId = 2L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 2L,
                            OperationId = 3L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 2L,
                            OperationId = 4L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 2L,
                            OperationId = 5L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 3L,
                            OperationId = 1L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 3L,
                            OperationId = 2L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 3L,
                            OperationId = 3L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 3L,
                            OperationId = 4L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 15L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 3L,
                            OperationId = 5L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 16L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 4L,
                            OperationId = 1L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 17L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 4L,
                            OperationId = 2L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 18L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 4L,
                            OperationId = 3L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 19L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 4L,
                            OperationId = 4L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 20L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 4L,
                            OperationId = 5L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 21L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 5L,
                            OperationId = 1L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 22L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 5L,
                            OperationId = 2L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 23L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 5L,
                            OperationId = 3L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 24L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 5L,
                            OperationId = 4L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 25L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 5L,
                            OperationId = 5L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 26L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 6L,
                            OperationId = 1L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 27L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 6L,
                            OperationId = 2L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 28L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 6L,
                            OperationId = 3L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 29L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 6L,
                            OperationId = 4L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 30L,
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 6L,
                            OperationId = 5L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 31L,
                            CreatedAt = new DateTime(2023, 2, 20, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 7L,
                            OperationId = 1L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2023, 2, 20, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 32L,
                            CreatedAt = new DateTime(2023, 2, 20, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 7L,
                            OperationId = 2L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2023, 2, 20, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 33L,
                            CreatedAt = new DateTime(2023, 2, 20, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 7L,
                            OperationId = 3L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2023, 2, 20, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 34L,
                            CreatedAt = new DateTime(2023, 2, 20, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 7L,
                            OperationId = 4L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2023, 2, 20, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 35L,
                            CreatedAt = new DateTime(2023, 2, 20, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 7L,
                            OperationId = 5L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2023, 2, 20, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 36L,
                            CreatedAt = new DateTime(2023, 2, 20, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 9L,
                            OperationId = 1L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2023, 2, 20, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 37L,
                            CreatedAt = new DateTime(2023, 2, 20, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 9L,
                            OperationId = 2L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2023, 2, 20, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 38L,
                            CreatedAt = new DateTime(2023, 2, 20, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 9L,
                            OperationId = 3L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2023, 2, 20, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 39L,
                            CreatedAt = new DateTime(2023, 2, 20, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 9L,
                            OperationId = 4L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2023, 2, 20, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = 40L,
                            CreatedAt = new DateTime(2023, 2, 20, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            ModuleId = 9L,
                            OperationId = 5L,
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            UpdatedAt = new DateTime(2023, 2, 20, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "security");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "security");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUserRole<string>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "security");
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.Auth.Roles.Role", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit")
                        .HasColumnName("is_system");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Role");

                    b.HasData(
                        new
                        {
                            Id = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            ConcurrencyStamp = "6acc130c-f695-4134-9e9c-19ba25872d52",
                            Name = "Super Admin",
                            NormalizedName = "SUPER ADMIN",
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            IsSystem = true,
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = "67df368b-c097-4020-b6b9-f2c03aaae7a8",
                            ConcurrencyStamp = "1d548e79-f43f-4452-af54-88327d81a3a4",
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            CreatedAt = new DateTime(2023, 9, 27, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            IsSystem = true,
                            UpdatedAt = new DateTime(2023, 9, 27, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = "fd44e5d3-57ed-4276-98b6-844f06045062",
                            ConcurrencyStamp = "d0926134-d4c9-4ce4-9802-3f1c6605a33b",
                            Name = "Content Creator",
                            NormalizedName = "CONTENT CREATOR",
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            IsSystem = true,
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            Id = "61580090-2de4-4f3a-8d93-34e32fc48ecb",
                            ConcurrencyStamp = "d65c8300-f921-4eb4-9241-98ddc63c50f5",
                            Name = "Editor",
                            NormalizedName = "EDITOR",
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            IsDeleted = false,
                            IsSystem = true,
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        });
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.Auth.Roles.UserRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserRole<string>");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("UserId1");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("UserRole");

                    b.HasData(
                        new
                        {
                            UserId = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            RoleId = "fd44e5d3-57ed-4276-98b6-844f06045062",
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            Id = 0L,
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            UserId = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            RoleId = "b17cc416-89b4-455d-a58a-4b4e8503e995",
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            Id = 0L,
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        },
                        new
                        {
                            UserId = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            RoleId = "61580090-2de4-4f3a-8d93-34e32fc48ecb",
                            CreatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8",
                            Id = 0L,
                            UpdatedAt = new DateTime(2021, 11, 15, 0, 53, 30, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "c1be5862-d402-4a31-b292-6aded859f7a8"
                        });
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.Auth.Roles.RoleTranslation", b =>
                {
                    b.HasOne("Boilerplate.Core.Entities.Auth.Roles.Role", "Role")
                        .WithMany("RoleTranslations")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.Auth.User", b =>
                {
                    b.OwnsMany("Boilerplate.Core.Entities.Auth.UserRefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<int>("RefreshTokenId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("refresh_token_id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("RefreshTokenId"), 1L, 1);

                            b1.Property<string>("Agent")
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)")
                                .HasColumnName("agent");

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime2")
                                .HasColumnName("created_on");

                            b1.Property<DateTime>("ExpiresOn")
                                .HasColumnType("datetime2")
                                .HasColumnName("expires_on");

                            b1.Property<string>("IpAdress")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ip_adress");

                            b1.Property<string>("RefreshToken")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)")
                                .HasColumnName("refresh_token");

                            b1.Property<DateTime?>("RevokedOn")
                                .HasColumnType("datetime2")
                                .HasColumnName("revoked_on");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("RefreshTokenId");

                            b1.HasIndex("UserId");

                            b1.ToTable("user_refresh_tokens", "security");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("Boilerplate.Core.Entities.Auth.UserValidationToken", "ValidationTokens", b1 =>
                        {
                            b1.Property<long>("TokenId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("token_id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("TokenId"), 1L, 1);

                            b1.Property<string>("Agent")
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)")
                                .HasColumnName("agent");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("nvarchar(6)")
                                .HasColumnName("code");

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime2")
                                .HasColumnName("created_on");

                            b1.Property<DateTime>("ExpiresOn")
                                .HasColumnType("datetime2")
                                .HasColumnName("expires_on");

                            b1.Property<string>("IpAdress")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ip_adress");

                            b1.Property<bool>("IsUsed")
                                .HasColumnType("bit")
                                .HasColumnName("is_used");

                            b1.Property<DateTime?>("RevokedOn")
                                .HasColumnType("datetime2")
                                .HasColumnName("revoked_on");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)")
                                .HasColumnName("token");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("TokenId");

                            b1.HasIndex("UserId");

                            b1.ToTable("user_validation_tokens", "security");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("RefreshTokens");

                    b.Navigation("ValidationTokens");
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.Departments.Department", b =>
                {
                    b.HasOne("Boilerplate.Core.Entities.Departments.Department", "MainDepartment")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("MainDepartment");
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.Departments.DepartmentTranslation", b =>
                {
                    b.HasOne("Boilerplate.Core.Entities.Departments.Department", "Department")
                        .WithMany("DepartmentTranslations")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.Departments.DepartmentUser", b =>
                {
                    b.HasOne("Boilerplate.Core.Entities.Departments.Department", "Department")
                        .WithMany("DepartmentUsers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Boilerplate.Core.Entities.Auth.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId");

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.Elements.ElementTranslation", b =>
                {
                    b.HasOne("Boilerplate.Core.Entities.Elements.Element", "Element")
                        .WithMany("ElementTranslations")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.Languages.LanguageTranslation", b =>
                {
                    b.HasOne("Boilerplate.Core.Entities.Languages.Language", "Language")
                        .WithMany("LanguageTranslations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.RolePermission", b =>
                {
                    b.HasOne("Boilerplate.Core.Entities.PermissionModule", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Boilerplate.Core.Entities.Auth.Roles.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Boilerplate.Core.Entities.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Boilerplate.Core.Entities.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Boilerplate.Core.Entities.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Boilerplate.Core.Entities.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.Auth.Roles.UserRole", b =>
                {
                    b.HasOne("Boilerplate.Core.Entities.Auth.Roles.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Roles_RoleId1");

                    b.HasOne("Boilerplate.Core.Entities.Auth.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId1");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.Auth.User", b =>
                {
                    b.Navigation("UserGroups");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.Departments.Department", b =>
                {
                    b.Navigation("DepartmentTranslations");

                    b.Navigation("DepartmentUsers");
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.Elements.Element", b =>
                {
                    b.Navigation("ElementTranslations");
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.Languages.Language", b =>
                {
                    b.Navigation("LanguageTranslations");
                });

            modelBuilder.Entity("Boilerplate.Core.Entities.Auth.Roles.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("RoleTranslations");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
